export const endpoints = [
  ['GET', '/api/v1/workspace', 'Workspace data', 'none', 'WorkspaceData'],
  [
    'GET',
    '/api/v1/profile/{username}',
    'Available profile',
    'username: 1–30 letters, digits, underscores or periods',
    'NormalizedProfile',
  ],
  [
    'GET',
    '/api/v1/profile/{username}/history',
    'Historical snapshots',
    'username; returns chronological observations',
    'Snapshot[]',
  ],
  [
    'GET',
    '/api/v1/profile/{username}/events',
    'Change events',
    'username; newest first, maximum 10,000',
    'TrackingEvent[]',
  ],
  [
    'GET',
    '/api/v1/profile/{username}/media',
    'Available media',
    'username; newest first, maximum 1,000 stored items',
    'Media[]',
  ],
  ['GET', '/api/v1/profile/{username}/analytics', 'Derived analytics', 'username', 'Analytics'],
  [
    'GET',
    '/api/v1/profile/{username}/stories',
    'Capability status',
    'username; unsupported in this provider',
    'UNSUPPORTED_CAPABILITY',
  ],
  [
    'POST',
    '/api/v1/profile/{username}/refresh',
    'Refresh observation',
    'username; no body; at most once per minute',
    '{ id, changed, profile }',
  ],
  ['GET', '/api/v1/media/{id}', 'Media detail', 'id: URL-encoded RIGtracker media ID', 'Media'],
  ['GET', '/api/v1/tracked', 'Tracking configurations', 'none', 'TrackedProfile[]'],
  [
    'POST',
    '/api/v1/tracked',
    'Create or update tracker',
    '{ username, interval_minutes: 60–10080, notify: boolean, threshold?: positive integer }',
    'TrackedProfile[]',
  ],
  [
    'PATCH',
    '/api/v1/tracked/{id}',
    'Edit tracking',
    '{ enabled?: boolean, interval_minutes?: 60–10080, notify?: boolean }',
    '{ updated: true }',
  ],
  [
    'DELETE',
    '/api/v1/tracked/{id}',
    'Remove tracker',
    'id; history preserved',
    '{ deleted: true }',
  ],
  [
    'GET',
    '/api/v1/compare',
    'Compare 2–5 distinct accounts',
    '?accounts=rigtracker_demo,northline_demo',
    '{ profile, history, growth, analytics }[]',
  ],
  [
    'POST',
    '/api/v1/link/inspect',
    'Normalize Instagram URL',
    '{ url: string, maximum 2048 characters }',
    'LinkInspection',
  ],
  ['GET', '/api/v1/saved', 'Saved accounts and tags', 'none', 'SavedProfile[]'],
  [
    'POST',
    '/api/v1/saved',
    'Save or edit bookmark',
    '{ username, notes?: string (2000), label?: string (80), tags?: string[] }',
    'SavedProfile[]',
  ],
  ['DELETE', '/api/v1/saved/{id}', 'Remove bookmark', 'id', '{ deleted: true }'],
  [
    'GET',
    '/api/v1/notifications',
    'Recent in-app notifications',
    'none; newest 200',
    'Notification[]',
  ],
  ['PATCH', '/api/v1/notifications', 'Mark all as read', 'no body', '{ updated: true }'],
  ['PATCH', '/api/v1/notifications/{id}', 'Mark one as read', 'id; no body', '{ updated: true }'],
  ['GET', '/api/v1/me/connections', 'Connections without secrets', 'none', 'Connection[]'],
  [
    'DELETE',
    '/api/v1/me/connections/{id}',
    'Disconnect locally',
    'id; pauses live trackers',
    '{ disconnected: true, note }',
  ],
  [
    'DELETE',
    '/api/v1/me/data',
    'Delete local account and data',
    'no body; irreversible',
    '{ deleted: true }',
  ],
  [
    'GET',
    '/api/auth/session',
    'Session identity and CSRF token',
    'session cookie',
    '{ user, csrf }',
  ],
  [
    'POST',
    '/api/auth/register',
    'Create RIGtracker account',
    '{ name?, email, password: 12–128 characters }',
    '{ user } + cookies',
  ],
  ['POST', '/api/auth/login', 'RIGtracker sign-in', '{ email, password }', '{ user } + cookies'],
  [
    'POST',
    '/api/auth/demo',
    'Create isolated fictional workspace',
    'no body; mock mode only',
    '{ user } + cookies',
  ],
  ['POST', '/api/auth/logout', 'End session', 'no body', '{ signed_out: true }'],
  [
    'POST',
    '/api/auth/instagram/start',
    'Begin Meta consent',
    'no body; Meta configuration required',
    '{ url }',
  ],
  [
    'GET',
    '/api/auth/instagram/callback',
    'Consume OAuth callback',
    '?state=...&code=... or error; session binding required',
    'Redirect to Settings',
  ],
  ['GET', '/health', 'Liveness', 'public, no secrets', '{ status: ok }'],
  [
    'GET',
    '/ready',
    'Database and Redis readiness',
    'public; returns 503 on failure',
    '{ status, database, cache }',
  ],
  [
    'POST',
    '/api/internal/tick',
    'Run due jobs',
    'worker Bearer token; internal route',
    '{ processed }',
  ],
] as const;
